# Generated by Django 4.2.7 on 2024-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_useractivity_delete_test_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='clintsemails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
            ],
        ),
       
    ]
